DROP TABLE personnes;
DROP TABLE stats;
DROP TABLE candidats;
CREATE TABLE personnes(L_name VARCHAR2(30) NOT NULL,F_NAME VARCHAR2(30) NOT NULL,LOGIN VARCHAR2(5) NOT NULL,PASSWORD VARCHAR2(40) NOT NULL,STATUS VARCHAR2(3) NOT NULL);
ALTER TABLE personnes ADD CONSTRAINT pk_personnes PRIMARY KEY(LOGIN);
CREATE TABLE candidats(CODE VARCHAR2(3) NOT NULL, F_NAME VARCHAR2(30) NOT NULL,L_name VARCHAR2(30) NOT NULL);
ALTER TABLE candidats ADD CONSTRAINT pk_candidats PRIMARY KEY(CODE);
CREATE TABLE stats(CODE VARCHAR2(3) NOT NULL, POINTS NUMBER(3) NOT NULL,STATUS VARCHAR2(3));
ALTER TABLE stats ADD (CONSTRAINT pk_stats PRIMARY KEY(CODE),CONSTRAINT fk_stats FOREIGN Key (CODE) REFERENCES candidats(CODE)ON DELETE CASCADE);